name: Test and Release

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  build-linux-binaries:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [i686-unknown-linux-gnu, i686-unknown-linux-musl, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo --target ${{ matrix.target }} build --release
    - name: Save
      run: mdkir -p release && cp target/${{ matrix.target }}/release/think-and-say release/think-and-say-${{ matrix.target }}

  check-release-binaries:
    needs: build-linux-binaries
    steps:
    - name: Check
      run: ls release
