name: Test and Release

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check format
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  
  build-linux-binaries:
    needs: build-and-test
    runs-on: ubuntu-latest
    container:
      image: ubuntu-latest
      volumes:
        - release-volume:/release
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl]
    steps:
    - uses: actions/checkout@v1
    - name: Install toolchain target
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }} --release
    - name: Save
      run: mkdir -p release && cp target/${{ matrix.target }}/release/think-and-say /release/think-and-say-${{ matrix.target }}

  check-release-binaries:
    needs: build-linux-binaries
    runs-on: ubuntu-latest
    container:
      image: ubuntu-latest
      volumes:
        - release-volume:/release
    steps:
    - name: Check
      run: ls /release
